global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'data-generator'
    static_configs:
      - targets: ['data-generator:9091']
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
